spring.application.name=aniseyir
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=someusername
spring.datasource.password=testpw
spring.jpa.hibernate.ddl-auto=update

jwt.secret=merhabalarbenruhicenet # base64 format?nda secret girilmeli
jwt.duration=31

argon2.saltLength=31
argon2.hashLength=31
argon2.parallelism=31
argon2.memory=31
argon2.iterations=31
https.enable=false
api.prefix=/api/v1